### ISSUE TITLE
bad marshal data error

### ISSUE THREAD

**Issue by Zoeybird** [Falldog/pyconcrete#6] opened 2017-03-10 12:47 UTC
Hi, I am getting an error while trying to import a .pye file encrypted using pyconcrete. Below is the error message.

ValueError                                Traceback (most recent call last)
<ipython-input-1-27c233467700> in <module>()
      1 import pyconcrete
----> 2 from muDetect import Temporal

C:\Anaconda2\lib\site-packages\pyconcrete\__init__.py in load_module(self, fullname)
     70             magic = 8
     71 
---> 72         code = marshal.loads(data[magic:])
     73 
     74         m = self.new_module(fullname, self.full_path, self.pkg_path)

ValueError: bad marshal data (unknown type code)

**Comment by Falldog** [comment] 2017-03-10 15:40
@Zoeybird which python version in your environment?

**Comment by fangchih** [comment] 2017-04-11 15:16
I also got this error, my python ver is 2.7.9

**Comment by Falldog** [comment] 2017-04-11 15:42
Reference by stackoverflow [thread](http://stackoverflow.com/questions/30861493/how-to-fix-python-valueerrorbad-marshal-data)
It's seems caused by build & run by different python version
ex: build .pye by python **2.7.8**, run .pye by python **2.7.9**

@fangchih Please help to make sure build & run on same python version
Or you can rebuild all `.pye`, and try again

**Comment by fangchih** [comment] 2017-04-11 16:19
@Falldog  thanks, I just found the root cause same as you said. 
Do you have any workaround on this? because the PROD's python is older than CI's python.

**Comment by Falldog** [comment] 2017-04-11 21:32
1. The easiest way is that make sure all python version sync.
2. Use [Vagrant](https://www.vagrantup.com/) or [docker](https://www.docker.com/) to process CI task to make sure python version is sync in VM env
3. Production environment is hard to control the python version, maybe you should try [PyInstaller](http://www.pyinstaller.org/) rather than pyconcrete

@fangchih I don't know how your Production or CI work
Maybe you can explain more detail then I can give you more suggestion.

**Comment by fangchih** [comment] 2017-04-12 09:26
@Falldog, thanks for your help...

My PROD is embedded linux box which have 32bit and 64bit os, so far we only have 2.7.9 because of our toolchian limitation.  

My approach now is use docker in CI to emulate PROD env, same as you mentioned.
I will also give PyInstaller a try, but seems pycontrete is more light weight to just meet my requirement. XD

**Comment by Falldog** [comment] 2017-04-12 10:11
@fangchih, sounds great! 
:)

@Zoeybird I will close this issue, cause the root cause should be run & build by different python version. If there is another root cause of the issue, you can reopen it.

**Closed by Falldog** 2017-04-12 10:11 UTC
Labels: need more information
