### ISSUE TITLE
ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by retsyo** [Falldog/pyconcrete#11] opened 2017-06-27 14:02 UTC
I use Mingw64+Msys2 to compile pyconcrete for `Python 3.4.4 |Anaconda 2.3.0 (64-bit)`

for `fib.py` file 
```python
def fib(n):
    if n<=1:
        return 1
    else:
        return fib(n-1) + fib(n-2)
```
is coded into pye as
`python pyconcrete-admin.py compile --source=fib.py  --pye`

but `test.py`
```python
import pyconcrete

import fib

for i in range(10):
    print ('fib(%2i) = %2i' %  (i, fib.fib(i)))
```
says
```bash
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    import fib
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "e:\prg\py\Anaconda3_64\lib\site-packages\_pyconcrete\pyconcrete\__init__
.py", line 72, in load_module
    code = marshal.loads(data[magic:])
ValueError: bad marshal data (unknown type code)
```

**Comment by Falldog** [comment] 2017-06-27 17:36
@retsyo I think its python version different issue, reference #6 
1. python pyconcrete-admin.py compile --source=fib.py --pye
2. python test.py
the version of python executor should be the same, or it will cause marshal parsed error

You can pull the latest code, I had just committed for add more error messages about different python version

**Comment by retsyo** [comment] 2017-06-28 03:41
```bash
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    from fib import fib
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "e:\prg\py\Anaconda3_64\lib\site-packages\_pyconcrete\pyconcrete\__init__
.py", line 63, in load_module
    self._validate_version(data)
  File "e:\prg\py\Anaconda3_64\lib\site-packages\_pyconcrete\pyconcrete\__init__
.py", line 95, in _validate_version
    raise ValueError("Python version doesn't match with magic: python(%d) != pye
(%d)" % (py_magic, pye_magic))
ValueError: Python version doesn't match with magic: python(3310) != pye(45114)
```

**Comment by Falldog** [comment] 2017-06-28 04:00
Your python execution version is 3310
But python execution version of compile pye is 45114
reference [PythonMagicNumberList](https://github.com/python/cpython/blob/55fe1ae9708d81b902b6fe8f6590e2a24b1bd4b0/Lib/importlib/_bootstrap_external.py#L224)

Python 3.4rc2 = 3310 
But there is no 45114, it may build by 3rd party 

Please make sure the compile pye & execution of python, should be the same version
Or it will cause marshal parse error

**Comment by retsyo** [comment] 2017-06-28 04:33
I use the same python(thus same verion) to compile pye & execute python. 

That is so strange

**Comment by Falldog** [comment] 2017-06-28 15:20
That's strange
I can't find the root cause by current information

Maybe you can introduce the full environment information to me
And I will need some time to build the environment by myself and then test on it

**Comment by Falldog** [comment] 2017-07-01 00:44
It should be built by different runtime for python & pyconcrete.
Reference: [stackoverflow-post](https://stackoverflow.com/questions/2817869/error-unable-to-find-vcvarsall-bat#answer-18045219)

**Closed by Falldog** 2017-07-01 00:44 UTC
Labels: MinGW
